version: '2'
services:
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    volumes:
      - './ui:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - api
  api:
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - './api:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5000:5000'
    environment:
        - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'