//Events
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";

//Competitions
export const LOAD_COMPETITIONS_SUCCESS = "LOAD_COMPETITIONS_SUCCESS";
export const DELETE_COMPETITION_SUCCESS = "DELETE_COMPETITION_SUCCESS";
export const ADD_COMPETITION_SUCCESS = "ADD_COMPETITION_SUCCESS";
export const EDIT_COMPETITION_SUCCESS = "EDIT_COMPETITION_SUCCESS";

//Criterias
export const ADD_CRITERIA_SUCCESS = "ADD_CRITERIA_SUCCESS";
export const EDIT_CRITERIA_SUCCESS = "EDIT_CRITERIA_SUCCESS";
export const DELETE_CRITERIA_SUCCESS = "DELETE_CRITERIA_SUCCESS";

//Judges
export const LOAD_JUDGES_SUCCESS = "LOAD_JUDGES_SUCCESS";
export const DELETE_JUDGE_SUCCESS = "DELETE_JUDGE_SUCCESS";
export const ADD_JUDGE_SUCCESS = "ADD_JUDGE_SUCCESS";
export const EDIT_JUDGE_SUCCESS = "EDIT_JUDGE_SUCCESS";

//ApiStatus
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
